name: CI
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - working-directory: core
        run: |
          npm run build
          npm run bundle
          npm run bundle:min
          npm run coverage

      - working-directory: www
        run: |
          npm run build
          npm run map
      
      - run: cp -rp core/coverage ./

      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@main

      - run: cp -rp www/build ./
      - run: cp -rp coverage build

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: build/CONTRIBUTORS.svg
          avatarSize: 42

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.6
        with:
          package-path: ./core/package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@v1.5.3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.5.3
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (renovate-bot|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: jaywcjlove/create-tag-action@v1.3.6
        with:
          package-path: ./core/package.json
          release: true
          body: |
            [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@b0r0/lily-text-editor@${{steps.changelog.outputs.version}}/file/README.md)

            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/uiwjs/lily-text-editor/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }} 

            ```bash
            npm i @b0r0/lily-text-editor@${{steps.changelog.outputs.version}}
            ```
            
            ${{ steps.changelog.outputs.changelog }}

      - name: 📦 @b0r0/lily-text-editor publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./core/package.json

    outputs:
      successful: ${{steps.create_tag.outputs.successful }}

  github-package:
    runs-on: ubuntu-18.04
    needs: build-deploy
    if: needs.build-deploy.outputs.successful
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@b0r0js'

      - run: npm install
      - working-directory: core
        run: |
          npm run build
          npm run bundle
          npm run bundle:min

      - name: Modify @b0r0/lily-text-editor => @b0r0js/lily-text-editor
        uses: jaywcjlove/github-action-package@main
        with:
          path: core/package.json
          data: |
            { "name": "@b0r0js/lily-text-editor" }
  
      - run: npm publish
        working-directory: core
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

